### ISSUE TITLE
Spotlight integration not working

### ISSUE THREAD

**Issue by alessandro-newzoo** [ruddarr/app#335]
Hello, and thank you for finally building an alternative to Lunasea - I absolutely love Ruddarr <3 

I noticed Spotlight integration isn't working for me. I'm not sure exactly what to expect, but when I search for a movie I have, it doesn't show up. It's not specific to any movie, none of the movies I have will show up.

Ruddarr `1.2.0`
iOS `18.0`
iPhone 14 Pro

![251C721B-6A50-4928-AB3E-EB6AE939F6B3_1_102_o](https://github.com/user-attachments/assets/0760a1bd-3675-4302-bcbd-b57377cb681b)
![685B085B-BDAF-454E-BD7A-64084F9312D1_1_102_o](https://github.com/user-attachments/assets/fc808972-a4a1-4074-92bc-8d9a7d312807)
![ScreenRecording_10-01-202410-43-49_1-ezgif com-resize](https://github.com/user-attachments/assets/f423aece-8b97-4698-b2b0-2a1e9feb68e8)

**Comment by tillkruss** [comment]
It takes a while to load all the posters. Scroll through your full library, or wait until the app fetched all content.

**Comment by alessandro-newzoo** [comment]
@tillkruss I'm not sure what you mean, I've installed the update when it came out, which was days ago, and I use the app daily (and scrolled through my library several times), so I take it that should be enough time for the app to fetch the library?

**Comment by tillkruss** [comment]
@alessandro-newzoo Can you send me a dump of your /series and /movie endpoints, I'll check if it contains any data/characters that might throw off the indexer.

**Comment by alessandro-newzoo** [comment]
@tillkruss here you go, hope it's what you asked for:
[sonarr_radarr_dump.zip](https://github.com/user-attachments/files/17230946/sonarr_radarr_dump.zip)

**Comment by tillkruss** [comment]
@alessandro-newzoo: Any chance you're seeing only movies or only shows index, but never both?

**Comment by tillkruss** [comment]
I pushed build 273 to TestFlight that resolved a bunch of Spotlight issues I've had myself.

**Comment by alessandro-newzoo** [comment]
Yesterday I've updated to the beta version 1.2.1 (273), cleared image cache, deleted spotlight index, browsed through all my tv shows and movies several times, even opened some, and let 24 hours pass, still no luck.

I haven't tested them all, but here are the results of the entries I've checked:

Show up:
- Severance (TV)
- Futurama (TV)
- Hotel cocaine (TV)
- Napoli magica (Movie)

Don't show up:
- Spirited Away (Movie)
- Ted (TV)
- Snowpiercer (TV)
- Pyramid Game (TV)
- Ripley (TV)
- Challengers (Movie)
- The zone of interest (Movie)
- Gran Torino (Movie)
- Broker (Movie)
- A man called Otto (Movie)
- Avatar (Movie)
- Race for glory (Movie)
- Atlas (Movie)

**Comment by tillkruss** [comment]
I've refactored the indexer in 1.3.0, if that doesn't work I'll need access to your instances to replicate this.

**Comment by tillkruss** [comment]
@alessandro-newzoo Too funny 😂

Does this link not work for you in a browser? https://discord.gg/UksvtDQUBA

**Comment by tillkruss** [comment]
Adding your instances indexes content just fine for me and shows up in the spotlight search. Must be a configuration or some kind of issue with your device. Sorry 🤷🏻‍♂️

```
[info] #movies: Fetched movies (count: 31)
[info] #spotlight: Indexing [Movie] (instance: BBF01273-6B4A-4DC1-9BEE-9C53CB501E79; count: 31)
[info] #spotlight: Indexed [Movie] (instance: BBF01273-6B4A-4DC1-9BEE-9C53CB501E79; count: 31)

[info] #series: Fetched series (count: 56)
[info] #spotlight: Indexing [Series] (instance: 72B64F1E-0310-4204-821D-50C56A17F67B; count: 56)
[info] #spotlight: Indexed [Series] (instance: 72B64F1E-0310-4204-821D-50C56A17F67B; count: 56)
```

**Comment by alessandro-newzoo** [comment]
> Does this link not work for you in a browser? https://discord.gg/UksvtDQUBA

Nope! I get this

![CleanShotX - Arc  10 10 2024 at 10-22-12 @2x](https://github.com/user-attachments/assets/4d43c159-88bd-4476-90fa-3a227e3141f9)

> Adding your instances indexes content just fine for me and shows up in the spotlight search. Must be a configuration or some kind of issue with your device. Sorry 🤷🏻‍♂️

😕

**Comment by alessandro-newzoo** [comment]
Update:
the link doesn't work from the browser, but if I add the server through the Discord app and paste the link there, it works 🤷🏻

Seems to be a problem on my end.
